# Do not edit this file manually. It is automatically generated.
# Edit 'capture-all.sh' instead.

source ../../definition_get_head.sh
source ../../definition_not_web_terminal.sh
source definitions.sh

stage_dir_with_scripts stage-without-checker
expect_exec -o "captured-data/k-0/stdout" -eempty tinvoke solution/correct1.cpp
expect_exec -o "captured-data/k-1/stdout" -eempty tinvoke solution/wrong1.cpp
expect_exec -o "captured-data/k-2/stdout" -eempty tinvoke solution/rte1.cpp
expect_exec -o "captured-data/k-3/stdout" -eempty tinvoke solution/slow1.cpp
expect_exec -o "captured-data/k-4/stdout" -eempty tinvoke solution/slow2.cpp
expect_exec -o "captured-data/k-5/stdout" -eempty tinvoke solution/correct1.py
expect_exec -o "captured-data/k-6/stdout" -eempty tinvoke solution/wrong1.py
expect_exec -o "captured-data/k-7/stdout" -eempty tinvoke solution/rte1.py
expect_exec -o "captured-data/k-8/stdout" -eempty tinvoke solution/slow1.py
expect_exec -o "captured-data/k-9/stdout" -eempty tinvoke -r solution/correct1.cpp
expect_exec -o "captured-data/k-10/stdout" -eempty tinvoke -r solution/wrong1.cpp
expect_exec -o "captured-data/k-11/stdout" -eempty tinvoke -r solution/rte1.cpp
expect_exec -o "captured-data/k-12/stdout" -eempty tinvoke -r solution/slow1.cpp
expect_exec -o "captured-data/k-13/stdout" -eempty tinvoke -r solution/slow2.cpp
expect_exec -oempty -eh2 "Solution file 'nonexist.cpp' not found." "Given address: 'solution/nonexist.cpp'" tinvoke solution/nonexist.cpp
expect_exec -oh "solution            compile[FAIL]" -eempty get_head 1 1 tinvoke solution/compile_error.cpp
expect_exec -o "captured-data/k-16/stdout" -eempty tinvoke solution/correct1-warn.cpp
expect_exec -o "captured-data/k-17/stdout" -eempty tinvoke --no-sol-compile solution/correct1-warn.cpp
expect_exec -o "captured-data/k-18/stdout" -eempty tinvoke -s solution/correct1-warn.cpp
expect_exec -oh3 "solution            compile[WARN]" "exit-code: 0" "warnings:" -eempty get_head 3 3 tinvoke -w solution/correct1-warn.cpp
expect_exec -o "captured-data/k-20/stdout" -eempty tinvoke --no-check solution/correct1.cpp
expect_exec -o "captured-data/k-21/stdout" -eempty tinvoke --no-check solution/rte1.cpp
expect_exec -o "captured-data/k-22/stdout" -eempty tinvoke --no-check solution/slow1.cpp
expect_exec -o "captured-data/k-23/stdout" -eempty tinvoke -r --no-check solution/correct1.cpp
expect_exec -o "captured-data/k-24/stdout" -eempty tinvoke -r --no-check solution/rte1.cpp
expect_exec -o "captured-data/k-25/stdout" -eempty tinvoke -r --no-check solution/slow1.cpp
expect_exec -o "captured-data/k-26/stdout" -eempty tinvoke solution/slow2.cpp -r --no-tle
expect_exec -o "captured-data/k-27/stdout" -eempty tinvoke solution/slow2.cpp -r --time-limit=4
expect_exec -o "captured-data/k-28/stdout" -eempty tinvoke solution/slow1.cpp -r --time-limit=4
expect_exec -o "captured-data/k-29/stdout" -eempty tinvoke solution/slow1.cpp -r --hard-time-limit=5
expect_exec -oempty -eh2 "Tests directory 'new-test-dir' not found." "Given address: 'new-test-dir'" tinvoke --tests-dir=new-test-dir solution/correct1.cpp
run_in_stage mkdir new-test-dir
expect_exec -oh2 "solution            compile[OK]" "" -eh2 "Error:" "Tests are not correctly generated." get_head 2 2 tinvoke --tests-dir=new-test-dir solution/correct1.cpp
run_in_stage rm -f tests/0-01.in
expect_exec -o "captured-data/k-32/stdout" -eh2 "Missing tests: 0-01" "Missing 1 test!" tinvoke -r solution/correct1.cpp
expect_exec -o "captured-data/k-33/stdout" -eh2 "Missing tests: 0-01" "Missing 1 test!" tinvoke -r -s solution/correct1.cpp
run_in_stage rm -f tests/1-01.out
expect_exec -o "captured-data/k-34/stdout" -eh2 "Missing tests: 0-01, 1-01" "Missing 2 tests!" tinvoke -r solution/correct1.cpp
expect_exec -o "captured-data/k-35/stdout" -eh2 "Missing tests: 0-01, 1-01" "Missing 2 tests!" tinvoke -r -s solution/correct1.cpp

stage_dir_with_scripts stage-with-checker
expect_exec -o "captured-data/k-36/stdout" -eempty tinvoke solution/correct1.cpp
expect_exec -o "captured-data/k-37/stdout" -eempty tinvoke solution/wrong1.cpp
expect_exec -o "captured-data/k-38/stdout" -eempty tinvoke solution/rte1.cpp
expect_exec -o "captured-data/k-39/stdout" -eempty tinvoke solution/slow1.cpp
expect_exec -o "captured-data/k-40/stdout" -eempty tinvoke -r solution/correct1.cpp
expect_exec -o "captured-data/k-41/stdout" -eempty tinvoke -r solution/wrong1.cpp
expect_exec -o "captured-data/k-42/stdout" -eempty tinvoke -r solution/rte1.cpp
expect_exec -o "captured-data/k-43/stdout" -eempty tinvoke -r solution/slow1.cpp
expect_exec -o "captured-data/k-44/stdout" -eempty tinvoke -r solution/slow2.cpp
expect_exec -o "captured-data/k-45/stdout" -eempty tinvoke --no-check solution/correct1.cpp
expect_exec -o "captured-data/k-46/stdout" -eempty tinvoke --no-check solution/rte1.cpp
expect_exec -o "captured-data/k-47/stdout" -eempty tinvoke --no-check solution/slow1.cpp
expect_exec -o "captured-data/k-48/stdout" -eempty tinvoke -r --no-check solution/correct1.cpp
expect_exec -o "captured-data/k-49/stdout" -eempty tinvoke -r --no-check solution/rte1.cpp
expect_exec -o "captured-data/k-50/stdout" -eempty tinvoke -r --no-check solution/slow1.cpp
run_in_stage rm -f checker/checker.cpp
expect_exec -o "captured-data/k-51/stdout" -eempty tinvoke solution/correct1.cpp
expect_exec -o "captured-data/k-52/stdout" -eempty tinvoke solution/correct1.cpp -r
expect_exec -o "captured-data/k-53/stdout" -eempty get_head 5 5 tinvoke solution/correct1.cpp -s
expect_exec -o "captured-data/k-54/stdout" -eempty get_head 5 5 tinvoke solution/correct1.cpp -sr
run_in_stage cp extra/checker-ce.cpp checker/checker.cpp
expect_exec -oh3 "solution            compile[OK]" "checker             compile[FAIL]" "exit-code: 2" -eempty get_head 3 3 tinvoke solution/correct1.cpp
run_in_stage cp extra/checker-warn.cpp checker/checker.cpp
expect_exec -o "captured-data/k-56/stdout" -eempty tinvoke solution/correct1.cpp
expect_exec -oh4 "solution            compile[OK]" "checker             compile[WARN]" "exit-code: 0" "warnings:" -eempty get_head 4 4 tinvoke solution/correct1.cpp -w
run_in_stage cp extra/checker-rte.cpp checker/checker.cpp
expect_exec -o "captured-data/k-58/stdout" -eempty tinvoke solution/correct1.cpp
expect_exec -o "captured-data/k-59/stdout" -eempty tinvoke solution/correct1.cpp -r
expect_exec -o "captured-data/k-60/stdout" -eempty get_head 7 7 tinvoke solution/correct1.cpp -s
expect_exec -o "captured-data/k-61/stdout" -eempty get_head 7 7 tinvoke solution/correct1.cpp -sr
run_in_stage cp extra/checker-fail.cpp checker/checker.cpp
expect_exec -o "captured-data/k-62/stdout" -eempty tinvoke solution/correct1.cpp
expect_exec -o "captured-data/k-63/stdout" -eempty tinvoke solution/correct1.cpp -r
expect_exec -o "captured-data/k-64/stdout" -eempty tinvoke solution/correct1.cpp -s
expect_exec -o "captured-data/k-65/stdout" -eempty tinvoke solution/correct1.cpp -sr
run_in_stage rm -rf checker
expect_exec -oh2 "solution            compile[OK]" "checker             compile[FAIL]" -eempty get_head 2 2 tinvoke solution/correct1.cpp
