# Do not edit this file manually. It is automatically generated.
# Edit 'capture-all.sh' instead.


source ../../definitions.sh
source ../definitions.sh

_TT_check_stage_not_in_a_tps_repo
stage_dir stage
expect_exec -o "captured-data/k1/stdout" -eempty run_ttis templates_dir/default/task-template-instantiate.sh -T templates_dir -t default new-dir
